name: Deployment
on:
  push:
    branches:
      - main
    paths:
      - "src/**.md"
      - "book.toml"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          docker build -t mdbook-builder .
          docker run --name mdbook-container mdbook-builder
      - name: Copy Artifacts (/book)
        run: docker cp mdbook-container:/book .
      
      - name: Checkout production branch
        uses: actions/checkout@v4
        with:
          ref: 'production'

      - name: Copy book to production
        run: |
          cp -r book/* .
          git config --global user.name 'Github Actions'
          git config --global user.email 'actions@github.com'
          git add .
          DATE=$(date+'%Y-%m-%d')
          git commit -m "Deploy book to production on ${DATE}"
          git push



