name: Deployment
on:
  push:
    branches:
      - main
    # paths:
    #   - "src/**.md"
    #   - "book.toml"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup mdbook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - name: Build docs
        run: |
          mdbook build -d dist

      - name: Archive dist
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout production branch
        uses: actions/checkout@v4
        with:
          ref: 'production'

      - name: Download dist
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist

      - name: Copy book to production
        run: |
          cp -r dist .
          git config --global user.name 'Github Actions'
          git config --global user.email 'actions@github.com'
          git add .
          DATE=$(date+'%Y-%m-%d')
          git commit -m "Deploy book to production on ${DATE}"
          git push



